# Generated by Django 4.2.6 on 2023-10-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=150)),
                ('Area_de_atuacao', models.CharField(max_length=30)),
                ('Nivel_de_senioridade', models.CharField(max_length=10)),
                ('Linguagem_Afinidade', models.CharField(max_length=50)),
                ('RA', models.CharField(max_length=9, unique=True)),
                ('Periodo', models.CharField(max_length=2)),
                ('Email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Aluno',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=50, unique=True)),
                ('Senha', models.CharField(max_length=50)),
                ('Nome', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Professor',
            },
        ),
    ]
